apiVersion: apps/v1
kind: Deployment
metadata:
  name: tshoot
  namespace: dev
spec:
  selector:
    matchLabels:
      app: tshoot
  template:
    metadata:
      labels:
        app: tshoot
    spec:
      containers:
      - name: tshoot
        image: nicolaka/netshoot
        command: ["sleep", "60000"]
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"

