apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: myapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        command: ["sleep", "5000"]
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "1"