apiVersion: v1
kind: LimitRange
metadata:
  name: default-limit
spec:
  limits:
    - default:
        memory: 500Mi
        cpu: 500Mi
      defaultRequest:
        memory: 50Mi
        cpu: 50M

      max:
        memory: 1Gi
        cpu: "600Mi"
      min:
        memory: 50Mi
        cpu: 50M
      type: Container