apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-green
  labels:
    app: myapp 
spec:
  replicas: 10
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
        version: v2
    spec:
      containers:
      - name: web
        image: sanjeevkt720/230-app:v2
