apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-rs
  labels:
    test: test
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      name: demo-web
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx-web
          image: nginx:1.25.0