apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
  namespace: dev
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
  
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["list", "get"]