apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-depl
spec:
  replicas: {{.Values.replicaCount | default 1}}
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: "{{.Values.image.repository}}:{{.Values.image.tag}}"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
